{{- range $recommend := $.Values.gorse.recommends }}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ printf "%s-%s" (include "gorse.worker.fullname" $ ) $recommend.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: sever
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not $.Values.worker.autoscaling.enabled }}
  replicas: {{ $.Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: worker
  {{- if $.Values.worker.updateStrategy }}
  {{- if (eq $.Values.worker.kind "Deployment") }}
  strategy: {{- toYaml $.Values.worker.updateStrategy | nindent 4 }}
  {{- else }}
  updateStrategy: {{- toYaml $.Values.worker.updateStrategy | nindent 4 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" $ | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- if $.Values.worker.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.worker.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if $.Values.worker.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.worker.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.worker.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" $.Values.worker.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $.Values.worker.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $.Values.worker.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.worker.podAffinityPreset "component" "worker" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.worker.podAntiAffinityPreset "component" "worker" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $.Values.worker.nodeAffinityPreset.type "key" $.Values.worker.nodeAffinityPreset.key "values" $.Values.worker.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if $.Values.worker.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" $.Values.worker.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-worker
          image: "{{ $.Values.worker.image.repository }}:{{ $.Values.worker.image.tag }}"
          imagePullPolicy: {{ $.Values.worker.image.pullPolicy }}
          command: 
              - "/usr/bin/gorse-worker"
              - "--master-host"
              - {{ printf "%s-master" (include "common.names.fullname" $) | quote}}
              - "--master-port"
              - {{ $.Values.master.service.ports.grpc | quote }}
              - "--jobs"
              - {{ $.Values.work.jobs | quote }}
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
          # TODO - We dont have a proper endpoint for health check
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: http
          #   initialDelaySeconds: 120
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 0            
          {{- if $.Values.worker.resources }}
          resources: {{- toYaml $.Values.worker.resources | nindent 12 }}
          {{- end }}
{{- end }}
